version: '3.8'

services:
  ghubscraper:
    build: .
    container_name: ghubscraper
    environment:
      - MONGO_URI=mongodb://ghubscraper:ghubscraper@mongo:27017/
    volumes:
      - ./:/home/nonroot/ghubscraper/
    # ports:
    depends_on:
      - mongo
    tty: true  # persist (should use 'sh' as entrypoint)
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghubscraper
      MONGO_INITDB_ROOT_PASSWORD: ghubscraper
    ports:
      - 27017:27017
    volumes:
      - ./mongodata/:/data/db
  api:
    build: api/.
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./api:/home/api/
    command: python manage.py runserver 0.0.0.0:8000
      # sh -c "
      #   python manage.py makemigrations &&
      #   python manage.py migrate &&
      #   python manage.py runserver 0.0.0.0:8000"
    tty: true
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=ghubscraper
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - 5432:5432
  scrapyd:
    build: scrapyd/.
    container_name: scrapyd
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - 6800:6800
    command: scrapyd


# scrapy crawl scraper -a start_urls=https://github.com/danilakritsky