version: '3.8'

services:

  # =======================
  
  scraper:
    build: scraper/.
    container_name: scraper    
    volumes:
      - ./scraper/:/home/scraper/
    command: scrapyd-deploy
    depends_on:
      - scrapyd
    tty: true  # persist (should use 'sh' as entrypoint)

  # =======================
  
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghubscraper
      MONGO_INITDB_ROOT_PASSWORD: ghubscraper
    ports:
      - 27017:27017
    volumes:
      - ./mongodata/:/data/db
  
  # =======================
  
  api:
    build: api/.
    container_name: api
    ports:
      - 8000:8000
    volumes:
       - ./api:/home/api
    # migrate here since migration depends on postgres
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    tty: true
    depends_on:
      - postgres
    links:
      - postgres:postgres
  
  # =======================
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=ghubscraper
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
  
  # =======================
  
  scrapyd:
    build: scrapyd/.
    container_name: scrapyd
    ports:
      - 6800:6800
    command: scrapyd
    tty: true
    depends_on:
      - mongo
      - api
    volumes:
      - ./scrapyd/logs/:/home/scrapyd/logs/
  # =======================

  scrapydweb:
    build: scrapydweb/.
    container_name: scrapydweb
    ports:
      - 5000:5000
    command: scrapydweb
    tty: true
    depends_on:
      - scrapyd
    volumes:
      - ./scrapydweb/:/home/scrapydweb/

# scrapy crawl scraper -a start_urls=https://github.com/danilakritsky