version: '3.8'

services:
  ghubscraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghubscraper
    environment:
      - MONGO_URI=mongodb://ghubscraper:ghubscraper@mongo:27017/
    volumes:
      - ./:/home/nonroot/ghubscraper/
    ports:
      - 5000:5000
    tty: true  # persist (should use 'sh' as entrypoint)
    command: sh -c "scrapyd-deploy; scrapydweb"
  scrapyd:
    build:
      context: .
      dockerfile: Dockerfile.scrapyd
    container_name: scrapyd
    ports:
      - 5990:5990
    tty: true
    # command: 
  db:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghubscraper
      MONGO_INITDB_ROOT_PASSWORD: ghubscraper
    ports:
      - 27017:27017
    volumes:
      - ./mongodata/:/data/db

# scrapy crawl scraper -a start_urls=https://github.com/danilakritsky